version: '2'
services:
  web:
    build: .
    environment:
      - 'MONGO_URL=mongodb://mongo/ethnexus'
      - 'PARITY_URL=http://parity:8545'
    ports:
      - "3001:3001"
    links:
      - mongo
      - parity
    restart: always
  parity:
    image: "ethcore/parity:stable-release"
    ports:
      - "8545:8545"
    volumes:
      - "~/.parity:/root/.parity"

    entrypoint: /build/parity/target/release/parity  --jsonrpc-interface '0.0.0.0' --jsonrpc-hosts all
  mongo:
    image: "mongo:3.4.1"
    volumes:
      - "~/.mongo:/data/db"
    command: mongod --storageEngine wiredTiger
