version: '2'
services:
  parity:
    image: "ethcore/parity:stable-release"
    ports:
      - "8545:8545"
    volumes:
      - "~/.parity:/root/.parity"

    entrypoint: /build/parity/target/release/parity  --jsonrpc-interface '0.0.0.0' --jsonrpc-hosts all
  mongo:
    image: "mongo:3.4.1"
    volumes:
      - "~/.mongo:/data/db"
    command: mongod --storageEngine wiredTiger
