version: '2'
services:
  parity:
    image: "ethcore/parity:stable-release"
    ports:
      - "8545:8545"
    volumes:
      - "~/.parity:/root/.parity"

    entrypoint: /build/parity/target/release/parity  --jsonrpc-interface '0.0.0.0' --jsonrpc-hosts all
  mongo:
    image: "mongo:3.4.1"
    volumes:
      - "~/.mongo:/data/db"
    ports:
      - "27017:27017"
    command: mongod --storageEngine wiredTiger
  compiler:
    image: antoniojuliano/ethnexus-compiler
    ports:
      - "3002:3002"
    volumes:
      - "~/.ethnexus-compiler:/home/ethnexus/app/bin/soljson/"
    restart: always
